# -*- coding: utf-8 -*-
"""face mask detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f7oU405xF84TqhOGLgoY9yBkZ3YN-LXN

Connect to drive
"""

from google.colab import drive

drive.mount('/content/gdrive')

from google.colab import drive
drive.mount('/content/drive')

"""Go to the folder of project"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/MyDrive

# Commented out IPython magic to ensure Python compatibility.
# %cd project

"""Download yolov7 from github"""

!git clone https://github.com/WongKinYiu/yolov7.git

"""Download requirements of yolo and connect to GPU"""

!pip install -r /content/gdrive/MyDrive/project/yolov7/requirements.txt
!pip install -r /content/gdrive/MyDrive/project/yolov7/requirements_gpu.txt

# Commented out IPython magic to ensure Python compatibility.
#   %cd yolov7

"""Train model to our data



"""

!python train.py --workers 1 --device 0 --batch-size 16 --epochs 50 --img 640 640 --data data/custom_data.yaml --name yolov7-custom --weights yolov7.pt

"""Detect the masks on video"""

!python detect.py --weights best.pt --conf 0.1 --img-size=640 --source 3.mp4

